---
- name: Test AWX Root Privilege
  hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: Show SSH user
      ansible.builtin.command: whoami
      become: false
      register: ssh_user
      changed_when: false

    - name: Show SSH user
      ansible.builtin.debug:
        msg: "SSH login user: {{ ssh_user.stdout }}"

    - name: Show effective user after sudo
      ansible.builtin.command: whoami
      register: become_user
      changed_when: false

    - name: Show effective identity
      ansible.builtin.command: id
      register: become_id
      changed_when: false

    - name: Display result
      ansible.builtin.debug:
        msg:
          - "SSH user: {{ ssh_user.stdout }}"
          - "Become user: {{ become_user.stdout }}"
          - "Become identity: {{ become_id.stdout }}"

    - name: Verify root
      ansible.builtin.assert:
        that:
          - become_user.stdout | trim == "root"
        fail_msg: "AWX is NOT becoming root."
        success_msg: "AWX successfully became root."
